version: '3.7'

services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    command: --check-caps false
    ports:
      - 1972
      - 52783:52773
      - 53773
    volumes:
      - ./:/irisdev/app

